# The URL the site will be built for
base_url = "https://bittervan.github.io"

compile_sass = true
title = "BITTERVAN'S BLOG"
description = ""
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
author = "bittervan"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "BITTERVAN'S BLOG"
